### ISSUE TITLE
Create React App 5 (CRA5) errors when using basis-theory-js

### ISSUE THREAD

**Issue by armsteadj1** [Basis-Theory/basis-theory-js#365]
There is a known issue with CRA5 when using a module that has a submodule using `cjs`. `axios` a library `basis-theory-js` is dependent on uses `cjs` and in version `1.1.3` broke CRA5 when being used as a submodule. This results in the following errors:

```jsx
Error: TypeError: Cannot read properties of undefined
(reading 'transformRequest')
at new BasisTheoryService (BasisTheoryService.js:34:1)
at new BasisTheoryTokens (BasisTheoryTokens.js:23:1)
at new Create (CrudBuilder.js:13:1)
at new Delete (CrudBuilder.js:46:1)
at new List (CrudBuilder.js:53:1)
at new BasisTheoryTokensElementsDelegate
(tokens.js:10:1)

at BasisTheoryReact.init (BasisTheory.js:80:1)
at async useBasisTheory.js:24:1
```

or

```jsx
Error: The Basis Theory SDK is not supported with CRA 5, downgrade to CRA 4 or see https://github.com/facebook/create-react-app/issues/11889#issuecomment-1114928008 for a workaround.
    at new BasisTheoryService (BasisTheoryService.js:27:1)
    at new BasisTheoryTokens (BasisTheoryTokens.js:23:1)
    at new Create (CrudBuilder.js:13:1)
    at new Delete (CrudBuilder.js:46:1)
    at new List (CrudBuilder.js:53:1)
    at new BasisTheoryTokensElementsDelegate (tokens.js:10:1)
    at BasisTheoryReact.init (BasisTheory.js:80:1)
    at async useBasisTheory.js:24:1
```

This is a CRA issue which is no longer being maintained we do not see the framework fixing this issue - because of this we (Basis Theory) do not want to pin our `axios` version to `1.1.2` as this will only be a short term solution until we are forced to upgrade `axios` in the future.

**Comment by armsteadj1** [comment]
**Option 1:** 

CRA is no longer officially maintained meaning one option is to downgrade to `react-scripts` to `4.0.3` which resolves the above issue.

**Option 2:** 

Use the workaround listed in the [[CRA5 issue comments](https://github.com/facebook/create-react-app/issues/11889#issuecomment-1114928008)](https://github.com/facebook/create-react-app/issues/11889#issuecomment-1114928008) with `craco` to overwrite the webpack settings for `CRA5`.  

**Option 3:** 

Use an older version of the Basis Theory library  `basis-theory-js` or `basis-theory-react` :

```jsx
"@basis-theory/basis-theory-js": "1.77.0"
```

```jsx
"@basis-theory/basis-theory-react": "1.12.1"
```

**Option 4:**

Use `overrides` on npm or `resolutions` on yarn to pin the `axios` to `1.1.2`:

**NPM:**

```jsx
"overrides": {
	"@basis-theory/basis-theory-js": {
		"axios": "1.1.2"
	}
},
```

**Yarn:**

```jsx
"resolutions": {
      "@basis-theory/basis-theory-js/axios": "1.1.2"
  },
```
